config/routes.rb
Rails.application.routes.draw do
  resources :gossips

  root 'gossips#index'

  get 'gossips/index'

  get 'gossips/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "Hello World"
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def show
      @gossip = Gossip.find(params[:id])
  end

  def edit
      @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
  if @gossip.update(gossip_params)
    redirect_to @gossip
  else
    render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip
    else
      render 'new'
    end
  end

  private

  def gossip_params
    params.require(:gossip).permit(:anonymous_author, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>

<h1>Editer Gossip</h1>

<%= form_with(model: @gossip, local: true) do |form| %>

  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :anonymous_author %><br>
    <%= form.text_field :anonymous_author %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Retour', gossips_path %>

app/views/gossips/index.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>

<h1>La liste des Gossips</h1>

<table>
  <tr>
    <th>anonymous_author</th>
    <th>content</th>
  </tr>

  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Montrer', gossip_path(gossip) %></td>
      <td><%= link_to 'Editer', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Detruire', gossip, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Nouveau Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>

<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :anonymous_author %>
  <%= f.text_area :content %>
  <%= f.submit "Créer" %>
<% end %>

app/views/gossips/show.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>

<p>
  <strong>Author:</strong>
  <%= @gossip.anonymous_author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<%= link_to 'Editer', edit_gossip_path(@gossip) %>
<%= link_to 'Retour', gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>